/**
 * Writes faucet-worker/src/reveals.generated.ts — the Worker's lookup from windowId to reveal.
 *
 *   pnpm gen-reveal-index
 *
 * The Worker cannot read the filesystem at runtime, so reveals have to be bundled. With six
 * windows that was six hand-written imports; at 120 it needs generating. Run this after
 * export-public, before deploying.
 */
import {readdirSync, writeFileSync} from 'node:fs';

const REVEAL_DIR = new URL('../data/reveals/', import.meta.url).pathname;
const OUT = new URL('../../faucet-worker/src/reveals.generated.ts', import.meta.url).pathname;

const files = readdirSync(REVEAL_DIR).filter((f) => f.endsWith('.json')).sort();

const imports = files
    .map((f, i) => `import r${i} from '../../worker/data/reveals/${f}';`)
    .join('\n');

const entries = files
    .map((f, i) => `    '${f.replace(/\.json$/, '').toLowerCase()}': r${i},`)
    .join('\n');

writeFileSync(
    OUT,
    `// GENERATED by \`pnpm gen-reveal-index\` — do not edit.
// Maps windowId (lowercase) to its reveal. Bundled because a Worker has no filesystem.
${imports}

export const REVEALS: Record<string, unknown> = {
${entries}
};

export const REVEAL_COUNT = ${files.length};
`,
);

console.log(`✅ wrote faucet-worker/src/reveals.generated.ts with ${files.length} reveals`);
